
[General]
	#How long to wait (in seconds) before seeding new growths if no existing spread is detected
	#Range: > 1
	seedTime = 60
	#How many chunks to seed when seeding new growths
	#Range: > 1
	seedChunks = 50
	#Maximum distance from a player to seed growths
	#Range: > 1
	seedRadius = 128
	#The speed at which dragonskin grows. 100 is roughly the speed of spreading grass
	#Range: > 0
	growthPercent = 100
	#This causes plague block spread to be batched and performed at once, with an interval of this many seconds. The overall growth rate should be roughly the same, but it might help with lag.
	#Range: > 0
	spreadDelay = 60
	#The maximum number of block spreads performed in a single update. This limits the total spread to an average of spreadCap per spreadDelay seconds. Lower this if you're getting a lot of lag/dropped ticks on spreading. (0=No limit)
	#Range: > 0
	spreadCap = 500
	#The radius, in blocks, that a beacon will blast dragonskin blocks overhead when placed.
	#Range: > 0
	beaconBlastRadius = 8
	#The speed at which dragonskin decays in heal mode. 100 is roughtly the speed that grass dies when covered. If decaying too much at once lags, try lowering this.
	#Range: 0 ~ 100
	decayPercent = 100
	#How often (percentage) a decaying skin block should drop a piece of dragonsscale (as opposed to just disappearing). Too high might lag the server.
	#Range: 0 ~ 100
	sloughPercent = 10
	#How quickly a decaying dragonscale block should turn into an ore. 100 means 'the moment it lands'. Technically this is the chance it has to change each time the block ticks.
	#Range: 0 ~ 100
	orePercent = 10
	#The height that the plague seeds at
	#Range: 0 ~ 319
	plagueHeight = 255
	#Start the world in heal mode. Perhaps you want to configure your pack to start the plague when a certain event happens. (The command /healplague off can start it.)
	healDefault = false
	#When dragonskin blocks decay, they decay in patches of connected blocks, rather than individual blocks
	patchyDecay = true
	#The blocks that might be released from Dragonscale. This can be a resource ID (minecraft:stone) or a tagentry (forge:ores/iron)
	dropBlocks = ["forge:ores/iron", "forge:ores/diamond", "forge:ores/gold"]
	#Display debugging data in the console
	debug = false

