
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = true
	#Message that displays when Teleport is blocked
	blockedmessage = "%dim% is closed without the %item%"
	#Title for the Advancements
	craftedmessage = "Unlock %dim%"
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "kubejs:end_orb"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_end"
	#Comma seperated list of Dimension Display Names
	dimnames = "The End"

